### ISSUE TITLE
connect_string for oraclepaas_java_service_instance

### ISSUE THREAD

**Issue by tseoracle** [hashicorp/go-oracle-terraform#178]
To use DB-SYSTEMS database for JCS, the payload should have "connectString" in "WLS" section and should NOT have "dbServiceName".
According to the doc,
https://www.terraform.io/docs/providers/oraclepaas/r/oraclepaas_java_service_instance.html#connect_string
"connect_string" should do the job.
But doesn't.
Front-end parser takes "connect_string"
>  weblogic_server.0.connect_string:                             "" => "mydb-scan.mynet.myvcn.oraclevcn.com:1521/mypdb.mynet.myvcn.oraclevcn.com"
But generated payload body doesn't have it.
Also no way to remove "dbServiceName" because "database{name=}" is mandatory parameter.
Please fix.

**Comment by mbfrahry** [comment]
Hey @tseoracle, I've got a [fix](https://github.com/terraform-providers/terraform-provider-oraclepaas/pull/59) for this on the provider that will be shipped in the next release

**Comment by mbfrahry** [comment]
Hey @tseoracle, this fix has been released in version 1.4.2 of the oraclepaas provider

**Comment by tseoracle** [comment]
"connect_string" still can't work.
It never be passed to PSM site as connectString parameter
2019-01-23T12:47:58.869-0800 [DEBUG] plugin.terraform-provider-oraclepaas_v1.4.2_x4: Body: {"availabilityDomain":"xxxx","backupDestination":"BOTH","cloudStorageContainer":"xxxxx","cloudStoragePassword":"xxxxx","cloudStorageUser":"xxxxx","components":,"WLS":{"adminPassword":"xxxxx","adminUserName":"weblogic","dbaName":"sys","dbaPassword":"xxxxx","domainMode":"PRODUCTION","shape":"VM.Standard2.2","adminPort":7001,"securedAdminPort":7002}},"edition":"EE",...
...
  weblogic_server.0.connect_string:                             "" => "ssssdb-scan.ssss02.vcnnonprod.oraclevcn.com:1521/pdb1.ssss02.vcnnonprod.oraclevcn.com"
  weblogic_server.0.database.#:                                 "" => "1"
  weblogic_server.0.database.0.hostname:                        "" => "<computed>"
  weblogic_server.0.database.0.password:                        "<sensitive>" => "<sensitive>"
  weblogic_server.0.database.0.username:                        "" => "sys"
  weblogic_server.0.domain.#:                                   "" => "1"
...
Error: Error applying plan:

1 error(s) occurred:

* oraclepaas_java_service_instance.ssssjcs1: 1 error(s) occurred:

* oraclepaas_java_service_instance.ssssjcs1: Error creating JavaServiceInstance: unable to create Java Service Instance "ssssjcs1": 400: {"details":{"message":"PSM-LCM-01001 Unable to submit request to create service [ssssjcs1] in domain [idcs-ba90ad8156664784b646d74f4b484597].  See the included validation errors for details.","issues":["[Both DB service name [dbServiceName] and connect string [connectString] cannot be null or empty]"]}}

**Comment by tseoracle** [comment]
v1.4.3 works.
Thank you.
